// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace CashCountDown.Controllers
{
    public partial class AuctionsController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public AuctionsController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected AuctionsController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult DeactivateConfirmed()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeactivateConfirmed);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.JsonResult PlaceBidAjax()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.PlaceBidAjax);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult SubmitOrder()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SubmitOrder);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult addtoList()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.addtoList);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.JsonResult statusupdate()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.statusupdate);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.JsonResult ourtime()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.ourtime);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public AuctionsController Actions { get { return MVC.Auctions; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Auctions";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Auctions";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string Details = "Details";
            public readonly string Create = "Create";
            public readonly string Edit = "Edit";
            public readonly string Deactivate = "Deactivate";
            public readonly string DeactivateConfirmed = "Deactivate";
            public readonly string PlaceBidAjax = "PlaceBidAjax";
            public readonly string SubmitOrder = "SubmitOrder";
            public readonly string addtoList = "addtoList";
            public readonly string statusupdate = "statusupdate";
            public readonly string ourtime = "ourtime";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string Details = "Details";
            public const string Create = "Create";
            public const string Edit = "Edit";
            public const string Deactivate = "Deactivate";
            public const string DeactivateConfirmed = "Deactivate";
            public const string PlaceBidAjax = "PlaceBidAjax";
            public const string SubmitOrder = "SubmitOrder";
            public const string addtoList = "addtoList";
            public const string statusupdate = "statusupdate";
            public const string ourtime = "ourtime";
        }


        static readonly ActionParamsClass_Details s_params_Details = new ActionParamsClass_Details();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Details DetailsParams { get { return s_params_Details; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Details
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_Create s_params_Create = new ActionParamsClass_Create();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Create CreateParams { get { return s_params_Create; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Create
        {
            public readonly string auction = "auction";
        }
        static readonly ActionParamsClass_Edit s_params_Edit = new ActionParamsClass_Edit();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Edit EditParams { get { return s_params_Edit; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Edit
        {
            public readonly string id = "id";
            public readonly string auction = "auction";
        }
        static readonly ActionParamsClass_Deactivate s_params_Deactivate = new ActionParamsClass_Deactivate();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Deactivate DeactivateParams { get { return s_params_Deactivate; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Deactivate
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_DeactivateConfirmed s_params_DeactivateConfirmed = new ActionParamsClass_DeactivateConfirmed();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeactivateConfirmed DeactivateConfirmedParams { get { return s_params_DeactivateConfirmed; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeactivateConfirmed
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_PlaceBidAjax s_params_PlaceBidAjax = new ActionParamsClass_PlaceBidAjax();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PlaceBidAjax PlaceBidAjaxParams { get { return s_params_PlaceBidAjax; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PlaceBidAjax
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_SubmitOrder s_params_SubmitOrder = new ActionParamsClass_SubmitOrder();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SubmitOrder SubmitOrderParams { get { return s_params_SubmitOrder; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SubmitOrder
        {
            public readonly string OrderContents = "OrderContents";
        }
        static readonly ActionParamsClass_addtoList s_params_addtoList = new ActionParamsClass_addtoList();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_addtoList addtoListParams { get { return s_params_addtoList; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_addtoList
        {
            public readonly string id = "id";
            public readonly string list = "list";
        }
        static readonly ActionParamsClass_statusupdate s_params_statusupdate = new ActionParamsClass_statusupdate();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_statusupdate statusupdateParams { get { return s_params_statusupdate; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_statusupdate
        {
            public readonly string tt = "tt";
            public readonly string ids = "ids";
        }
        static readonly ActionParamsClass_ourtime s_params_ourtime = new ActionParamsClass_ourtime();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ourtime ourtimeParams { get { return s_params_ourtime; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ourtime
        {
            public readonly string TheirTime = "TheirTime";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Create = "Create";
                public readonly string Delete = "Delete";
                public readonly string Details = "Details";
                public readonly string Edit = "Edit";
                public readonly string Index = "Index";
                public readonly string NotActive = "NotActive";
            }
            public readonly string Create = "~/Views/Auctions/Create.cshtml";
            public readonly string Delete = "~/Views/Auctions/Delete.cshtml";
            public readonly string Details = "~/Views/Auctions/Details.cshtml";
            public readonly string Edit = "~/Views/Auctions/Edit.cshtml";
            public readonly string Index = "~/Views/Auctions/Index.cshtml";
            public readonly string NotActive = "~/Views/Auctions/NotActive.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_AuctionsController : CashCountDown.Controllers.AuctionsController
    {
        public T4MVC_AuctionsController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Details(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Details);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Create()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Create);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Create(CashCountDown.Models.Auction_Create auction)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Create);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "auction", auction);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Edit(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Edit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Edit(CashCountDown.Models.Auction_Edit auction)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Edit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "auction", auction);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Deactivate(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Deactivate);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult DeactivateConfirmed(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeactivateConfirmed);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            return callInfo;
        }

        public override System.Web.Mvc.JsonResult PlaceBidAjax(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.PlaceBidAjax);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult SubmitOrder(CashCountDown.Models.SubmitOrder OrderContents)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SubmitOrder);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "OrderContents", OrderContents);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult addtoList(int id, string list)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.addtoList);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "list", list);
            return callInfo;
        }

        public override System.Web.Mvc.JsonResult statusupdate(System.DateTime tt, System.Array ids)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.statusupdate);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "tt", tt);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "ids", ids);
            return callInfo;
        }

        public override System.Web.Mvc.JsonResult ourtime(System.DateTime TheirTime)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.ourtime);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "TheirTime", TheirTime);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
