// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace T4MVC
{
    public class SharedController
    {

        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _AuctionCard = "_AuctionCard";
                public readonly string _BidHistory = "_BidHistory";
                public readonly string _BillingAddr = "_BillingAddr";
                public readonly string _ChangePasswordPartial = "_ChangePasswordPartial";
                public readonly string _EditAutoBid = "_EditAutoBid";
                public readonly string _ExternalLoginsListPartial = "_ExternalLoginsListPartial";
                public readonly string _Featured = "_Featured";
                public readonly string _Footer = "_Footer";
                public readonly string _Header = "_Header";
                public readonly string _HorizantalAuctionList = "_HorizantalAuctionList";
                public readonly string _ItemBids = "_ItemBids";
                public readonly string _Layout = "_Layout";
                public readonly string _LoginPartial = "_LoginPartial";
                public readonly string _NewAutoBid = "_NewAutoBid";
                public readonly string _PayNow = "_PayNow";
                public readonly string _PlaceBid = "_PlaceBid";
                public readonly string _PlaceOrder = "_PlaceOrder";
                public readonly string _RecentBids = "_RecentBids";
                public readonly string _RemoveExternalLoginsPartial = "_RemoveExternalLoginsPartial";
                public readonly string _SetPasswordPartial = "_SetPasswordPartial";
                public readonly string _ShippingAddr = "_ShippingAddr";
                public readonly string _VerticalAuctionList = "_VerticalAuctionList";
                public readonly string Error = "Error";
                public readonly string Index = "Index";
            }
            public readonly string _AuctionCard = "~/Views/Shared/_AuctionCard.cshtml";
            public readonly string _BidHistory = "~/Views/Shared/_BidHistory.cshtml";
            public readonly string _BillingAddr = "~/Views/Shared/_BillingAddr.cshtml";
            public readonly string _ChangePasswordPartial = "~/Views/Shared/_ChangePasswordPartial.cshtml";
            public readonly string _EditAutoBid = "~/Views/Shared/_EditAutoBid.cshtml";
            public readonly string _ExternalLoginsListPartial = "~/Views/Shared/_ExternalLoginsListPartial.cshtml";
            public readonly string _Featured = "~/Views/Shared/_Featured.cshtml";
            public readonly string _Footer = "~/Views/Shared/_Footer.cshtml";
            public readonly string _Header = "~/Views/Shared/_Header.cshtml";
            public readonly string _HorizantalAuctionList = "~/Views/Shared/_HorizantalAuctionList.cshtml";
            public readonly string _ItemBids = "~/Views/Shared/_ItemBids.cshtml";
            public readonly string _Layout = "~/Views/Shared/_Layout.cshtml";
            public readonly string _LoginPartial = "~/Views/Shared/_LoginPartial.cshtml";
            public readonly string _NewAutoBid = "~/Views/Shared/_NewAutoBid.cshtml";
            public readonly string _PayNow = "~/Views/Shared/_PayNow.cshtml";
            public readonly string _PlaceBid = "~/Views/Shared/_PlaceBid.cshtml";
            public readonly string _PlaceOrder = "~/Views/Shared/_PlaceOrder.cshtml";
            public readonly string _RecentBids = "~/Views/Shared/_RecentBids.cshtml";
            public readonly string _RemoveExternalLoginsPartial = "~/Views/Shared/_RemoveExternalLoginsPartial.cshtml";
            public readonly string _SetPasswordPartial = "~/Views/Shared/_SetPasswordPartial.cshtml";
            public readonly string _ShippingAddr = "~/Views/Shared/_ShippingAddr.cshtml";
            public readonly string _VerticalAuctionList = "~/Views/Shared/_VerticalAuctionList.cshtml";
            public readonly string Error = "~/Views/Shared/Error.cshtml";
            public readonly string Index = "~/Views/Shared/Index.cshtml";
            static readonly _EditorTemplatesClass s_EditorTemplates = new _EditorTemplatesClass();
            public _EditorTemplatesClass EditorTemplates { get { return s_EditorTemplates; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _EditorTemplatesClass
            {
                public readonly string Color = "Color";
                public readonly string Date = "Date";
                public readonly string DateTime_Local = "DateTime-Local";
                public readonly string DateTime = "DateTime";
                public readonly string EmailAddress = "EmailAddress";
                public readonly string Month = "Month";
                public readonly string Number = "Number";
                public readonly string PhoneNumber = "PhoneNumber";
                public readonly string Search = "Search";
                public readonly string Time = "Time";
                public readonly string _Url = "Url";
                public readonly string Week = "Week";
            }
        }
    }

}

#endregion T4MVC
#pragma warning restore 1591
